services:
  - type: worker
    name: BOT_TEL
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "5953044720"
      - key: DATABASE_PATH
        value: database/bot.db
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_FILE_SIZE_MB
        value: "2048"
      - key: MAX_ZIP_ENTRIES
        value: "20000"
      - key: RENDER_EXTERNAL_URL
        value: https://bot-tel-x1w3.onrender.com
